pipeline {
    agent any
    
    stages {
        stage('Checkout') { 
            steps {
                git credentialsId: "${github_creds}" , url: "${github_repo}" 
            }
        }
        stage('hello') { 
            steps {
                sh 'hello world' 
            }
        }
    }
}
